

exports.DoSomething = async (req, res, next) => {
  try {

  } catch (err) {
    console.log("erreur:",err);
  }
}